repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: tflint
      args:
        - "--config=.tflint.hcl"
    - id: terraform-validate
    - id: terraform-fmt
    - id: gofmt
    - id: golint

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-system
      args: ["markdown", "--output-file", "README.md", "./"]

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.0.791
  hooks:
    - id: checkov
      args: [--external-checks-dir, 'policies', --framework, 'terraform']
  # to run this manually:
  # checkov -d ./ --framework terraform --external-checks-dir policies
